name: Setup Repository
description: Install dependencies and perform setup for https://github.com/tanishqmanuja/valorant-api-client

inputs:
  pnpm-version:
    description: PNPM version
    default: "8"
  node-version:
    description: Node.js version
    default: lts/*

runs:
  using: composite

  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node (${{ inputs.node-version }})
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile