name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "examples/**"
      - "README.md"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "examples/**"
      - "README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Format Check
        run: bun turbo format:check

      - name: Type Check
        run: bun turbo type:check

      - name: Type Check (Package)
        run: bun turbo type:check:package
