name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "assets/**"
      - "README.md"
      - ".github/README.md"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "assets/**"
      - "README.md"
      - ".github/README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Repository
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm turbo build
