name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump Type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Set Git User
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Set NPM Config
        run: npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Bump Version
        run: |
          npm version ${{ github.event.inputs.bump }} -m "chore: bump version"

      - name: Build
        run: bun turbo build

      - name: Publish
        run: npm publish --provenance --access public

      - name: Commit
        run: git push --follow-tags

      - name: Release Notes
        run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pack `.tgz` file
        run: |
          npm pack
          mv *.tgz package.tgz

      - name: Upload `.tgz` to GitHub Release
        run: gh release upload $(git describe --tags --abbrev=0) package.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
